version: '3.1'

services:
  cassandra:
    image: cassandra:latest

  seedcass:
    image: seedcass:test
    environment:
      CON_POINT: cassandra
      KEYSPACE: nearbytrevor
    depends_on:
      - cassandra
    command: npm run-script initCass

    
